# Enhanced ForexAI-EA Configuration v2.0
# File: config/enhanced_settings.yaml

project:
  name: "ForexAI-EA Enhanced"
  version: "2.0.0"
  environment: "development"
  phase: "Phase 2 - Volume Profile Integration"

# Enhanced AI Engine Configuration
ai_engine:
  version: "2.0.0"
  
  # Ensemble Model Configuration
  ensemble:
    models:
      random_forest:
        n_estimators: 200
        max_depth: 15
        min_samples_split: 10
        min_samples_leaf: 5
        class_weight: "balanced"
        weight: 0.4
      
      xgboost:
        n_estimators: 150
        max_depth: 8
        learning_rate: 0.1
        subsample: 0.8
        colsample_bytree: 0.8
        weight: 0.4
      
      logistic_regression:
        max_iter: 1000
        class_weight: "balanced"
        weight: 0.2
    
    voting_strategy: "soft"  # Use probability-based voting
    confidence_threshold: 0.65
  
  # Enhanced Feature Engineering
  features:
    total_count: 65
    
    # Feature weights for different components
    weights:
      technical_indicators: 0.4   # Original Phase 1 features
      volume_profile: 0.3         # NEW: Volume Profile features
      vwap_analysis: 0.2          # NEW: VWAP features
      advanced_combinations: 0.1   # NEW: Enhanced combinations
    
    # Volume Profile Configuration
    volume_profile:
      enabled: true
      lookback_period: 200
      num_price_levels: 100
      value_area_percent: 0.70
      min_volume_percentage: 2.0
      
    # VWAP Configuration
    vwap:
      enabled: true
      periods: [20, 50]           # Rolling VWAP periods
      bands_std_multiplier: 2.0   # Standard deviation for bands
      session_vwap: true          # Calculate session VWAP
      
    # Technical Indicators (Phase 1)
    technical:
      ema_periods: [9, 21, 50, 200]
      rsi_period: 14
      macd: [12, 26, 9]
      bollinger_bands: [20, 2]
      atr_period: 14
      stochastic: [14, 3, 3]
      williams_r: 14

# Enhanced Signal Filtering
signal_filtering:
  enabled: true
  
  # Multi-layer filtering system
  filters:
    confidence_filter:
      enabled: true
      min_confidence: 0.65
    
    model_consensus:
      enabled: true
      min_agreement: 0.6  # 60% of models must agree
    
    volume_profile_filter:
      enabled: true
      max_poc_distance: 0.005      # 0.5% max distance from POC
      require_strong_profile: true  # Require strong VP data
      min_profile_strength: 0.02
    
    vwap_filter:
      enabled: true
      trend_alignment: true        # Require VWAP trend alignment
      band_position_limits: true   # Don't trade at extreme band positions
      multi_timeframe_check: true
    
    market_structure_filter:
      enabled: true
      momentum_alignment: true     # Check momentum confluence
      support_resistance: true    # Avoid trading near S/R levels
    
    risk_filter:
      enabled: true
      max_volatility_regime: 2.0  # Don't trade in extreme volatility
      rsi_extremes: true          # Avoid RSI extremes

# Socket Server Configuration
socket_server:
  version: "2.0.0"
  host: "localhost"
  port: 8888
  max_connections: 10
  timeout: 30
  
  # Enhanced capabilities
  capabilities:
    volume_profile: true
    vwap_analysis: true
    ensemble_models: true
    enhanced_filtering: true
    market_structure: true
    real_time_analysis: true
  
  # Data management
  data:
    max_bars_stored: 500
    symbols: ["EURUSD", "GBPUSD", "USDJPY", "USDCHF", "AUDUSD"]
    
  # Performance monitoring
  monitoring:
    track_predictions: true
    track_performance: true
    log_enhanced_features: true

# Trading Configuration (Enhanced)
trading:
  version: "2.0.0"
  
  # Risk Management (Enhanced)
  risk_management:
    position_sizing: "kelly_criterion"
    base_risk_percent: 0.015      # 1.5% base risk
    max_risk_percent: 0.02        # 2% maximum risk
    max_daily_risk: 0.05          # 5% daily limit
    max_positions: 4
    max_correlation: 0.7
    
    # Enhanced risk controls
    enhanced_controls:
      volume_profile_adjustment: true    # Adjust risk based on VP context
      vwap_distance_factor: true        # Adjust based on VWAP distance
      volatility_scaling: true          # Scale risk with volatility
      session_based_risk: true          # Different risk per session
  
  # Position Management (Enhanced)  
  position_management:
    stop_loss:
      method: "atr_based"
      atr_multiplier: 2.0
      min_pips: 10
      
    take_profit:
      method: "atr_based"
      atr_multiplier: 3.0
      min_pips: 15
      
    trailing_stop:
      enabled: true
      atr_multiplier: 1.5
      
    # Enhanced position management
    enhanced_management:
      volume_profile_exits: true     # Use VP levels for exits
      vwap_based_targets: true       # VWAP-based profit targets
      market_structure_exits: true   # Structure-based exits

# Session Analysis (Enhanced)
session_analysis:
  enabled: true
  
  sessions:
    asian:
      start_hour: 22
      end_hour: 8
      characteristics:
        volatility: "low"
        trend_strength: "weak"
        range_bound: true
      risk_multiplier: 0.8
      preferred_pairs: ["USDJPY", "AUDUSD"]
      
    london:
      start_hour: 8
      end_hour: 17
      characteristics:
        volatility: "medium"
        trend_strength: "strong"
        breakouts: true
      risk_multiplier: 1.0
      preferred_pairs: ["EURUSD", "GBPUSD", "USDCHF"]
      
    newyork:
      start_hour: 13
      end_hour: 22
      characteristics:
        volatility: "high"
        trend_strength: "very_strong"
        momentum: true
      risk_multiplier: 1.2
      preferred_pairs: ["EURUSD", "GBPUSD", "USDJPY"]
      
    overlap:
      london_newyork:
        start_hour: 13
        end_hour: 17
        enhanced_opportunities: true
        risk_multiplier: 1.3

# Enhanced Logging
logging:
  version: "2.0.0"
  level: "INFO"
  
  files:
    main: "data/logs/enhanced_forexai_ea.log"
    ai_engine: "data/logs/enhanced_ai_engine.log"
    volume_profile: "data/logs/volume_profile.log"
    vwap: "data/logs/vwap_analysis.log"
    socket_server: "data/logs/enhanced_socket_server.log"
    trading: "data/logs/enhanced_trading.log"
    
  settings:
    max_file_size: "20MB"
    backup_count: 10
    rotation: "daily"
    
  # Enhanced logging components
  components:
    ai_predictions: true
    volume_profile_analysis: true
    vwap_calculations: true
    enhanced_filtering: true
    model_performance: true
    feature_importance: true
    ensemble_voting: true
    signal_filtering: true

# Model Persistence
model_storage:
  base_path: "data/models/"
  enhanced_model_file: "enhanced_ai_model.pkl"
  backup_models: true
  max_backups: 5
  
  auto_save:
    enabled: true
    save_after_training: true
    save_interval_hours: 24
    
  model_validation:
    enabled: true
    min_accuracy: 0.70
    min_cross_validation: 0.65
    require_volume_profile: true
    require_vwap: true

# Performance Monitoring (Enhanced)
performance_monitoring:
  enabled: true
  version: "2.0.0"
  
  metrics:
    prediction_accuracy: true
    signal_distribution: true
    confidence_statistics: true
    filter_effectiveness: true
    volume_profile_usage: true
    vwap_usage: true
    ensemble_performance: true
    
  tracking:
    real_time: true
    historical: true
    max_history_days: 30
    
  alerts:
    accuracy_threshold: 0.60     # Alert if accuracy drops below 60%
    error_rate_threshold: 0.10   # Alert if error rate exceeds 10%
    confidence_threshold: 0.50   # Alert if avg confidence drops below 50%
    
  reporting:
    daily_summary: true
    weekly_analysis: true
    performance_dashboard: true

# Enhanced Backtesting
backtesting:
  enabled: true
  version: "2.0.0"
  
  settings:
    initial_balance: 10000
    risk_per_trade: 0.02
    commission: 0.0001          # 1 pip commission
    slippage: 0.0001            # 1 pip slippage
    
  enhanced_features:
    volume_profile_context: true
    vwap_analysis: true
    session_awareness: true
    market_structure: true
    
  validation:
    walk_forward: true
    cross_validation: true
    monte_carlo: true
    stress_testing: true
    
  metrics:
    - "total_return"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
    - "calmar_ratio"
    - "sortino_ratio"
    - "volume_profile_performance"
    - "vwap_performance"

# Phase 2 Specific Settings
phase_2:
  status: "active"
  completion_percentage: 100
  
  implemented_features:
    volume_profile_engine: true
    vwap_calculator: true
    enhanced_feature_engineer: true
    ensemble_ai_engine: true
    enhanced_socket_server: true
    
  next_phase:
    phase: "Phase 2 Week 7-8"
    focus: "Smart Money Concepts (SMC)"
    estimated_start: "2025-06-15"
    
  performance_targets:
    prediction_accuracy: 0.80    # Target 80%+ with ensemble
    feature_count: 65            # Achieved: 65+ features
    response_time_ms: 150        # Target <150ms
    uptime_percentage: 99.9      # Target 99.9%

# Development Settings
development:
  debug_mode: false
  testing_mode: false
  verbose_logging: true
  
  validation:
    strict_validation: true
    feature_validation: true
    model_validation: true
    
  optimization:
    memory_optimization: true
    cpu_optimization: true
    network_optimization: true

# Deployment Settings
deployment:
  environment: "development"    # development, testing, production
  version: "2.0.0"
  
  requirements:
    python_version: "3.8+"
    memory_gb: 4
    cpu_cores: 2
    disk_space_gb: 10
    
  dependencies:
    core:
      - "numpy>=1.21.0"
      - "pandas>=1.3.0"
      - "scikit-learn>=1.0.0"
      - "xgboost>=1.5.0"
      - "pyyaml>=6.0"
      - "joblib>=1.1.0"
    
    enhanced:
      - "lightgbm>=3.3.0"      # For future SMC models
      - "matplotlib>=3.5.0"    # For visualization
      - "plotly>=5.0.0"        # For dashboards
      
  validation_checks:
    - "Python environment"
    - "Required packages"
    - "Model files"
    - "Configuration files"
    - "Log directories"
    - "Data directories"